from textwrap import dedent
from datetime import datetime
import sys

from ipart import opart

try:
    N = int(sys.argv[1])
except ValueError:
    print(f"ERROR: Attempting to generate flavor structure when FLAV={sys.argv[1]} is not a simple number of pions")
    sys.exit(1)

structs = {}


for part in opart(N, lambda x: x>1):
    part.reverse()

    tag = 'x'.join(str(p) for p in part)
    structs[tag] = []

    idx = 1
    for p in part:
        structs[tag].append(f"Tr({','.join(f'f{i}' for i in range(idx, idx+p))})")
        idx += p

endl = '\n        '
with open(f"flavs/flav{N}.hf", 'w') as out:
    print(dedent(f"""\
        * Generated by make_flav.py on {datetime.now().strftime('%c')}
        #define FLAVS{N} "{','.join(structs.keys())}"
        #define PKE{N} "{','.join(['p'] * N)}"
        {endl.join(f'#define Tr{tag} "' + '*'.join(traces) + '"' for tag,traces in structs.items())}
        #do FLAV={{`FLAVS{N}'}}
            #procedure Srel`FLAV'
            #endprocedure
        #enddo"""), file=out)
